"""init

Revision ID: 01c143caaef0
Revises: 
Create Date: 2025-09-27 10:46:00.691453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01c143caaef0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_index('ix_chatrooms_id', table_name='chatrooms')
    op.drop_table('chatrooms')
    op.drop_index('ix_messages_id', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_from_user', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('parent_message_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('chatroom_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'COMPLETED', 'PROCESSING', 'FAILED', name='enummessagestatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['chatroom_id'], ['chatrooms.id'], name='messages_chatroom_id_fkey'),
    sa.ForeignKeyConstraint(['parent_message_id'], ['messages.id'], name='messages_parent_message_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='messages_pkey')
    )
    op.create_index('ix_messages_id', 'messages', ['id'], unique=True)
    op.create_table('chatrooms',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='chatrooms_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='chatrooms_pkey')
    )
    op.create_index('ix_chatrooms_id', 'chatrooms', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('mobile_number', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('mobile_number', name='users_mobile_number_key')
    )
    # ### end Alembic commands ###
